<a href="https://colab.research.google.com/github/Somali19/18CSE119/blob/main/Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ASSIGNMENT - 2**

**NAME : SOMALI PATTJOSHI**

**ROLL NUMBER : 18CSE119**

**SECTION : B**

**SUBJECT : DMDW LAB**

-> Download a dataset from kaggle and upload it in jupyter
notebook or google colab. Perform any random operation on
the dataset.

Pandas

In [1]:
import pandas as pd


In [2]:
from google.colab import files
uploaded = files.upload()

Saving dataset.csv to dataset (2).csv


In [3]:
import io
df = pd.read_csv(io.BytesIO(uploaded['dataset.csv']))  #read the csv file
df

Overall rank  ... Perceptions of corruption
0               1  ...                     0.393
1               2  ...                     0.410
2               3  ...                     0.341
3               4  ...                     0.118
4               5  ...                     0.298
..            ...  ...                       ...
151           152  ...                     0.411
152           153  ...                     0.147
153           154  ...                     0.025
154           155  ...                     0.035
155           156  ...                     0.091

[156 rows x 9 columns]

In [4]:
df.index  

RangeIndex(start=0, stop=156, step=1)

In [5]:
df.head() #first five rows of dataframe

Overall rank Country or region  ...  Generosity  Perceptions of corruption
0             1           Finland  ...       0.153                      0.393
1             2           Denmark  ...       0.252                      0.410
2             3            Norway  ...       0.271                      0.341
3             4           Iceland  ...       0.354                      0.118
4             5       Netherlands  ...       0.322                      0.298

[5 rows x 9 columns]

In [6]:
df.tail() #last five row of dataframe

Overall rank  ... Perceptions of corruption
151           152  ...                     0.411
152           153  ...                     0.147
153           154  ...                     0.025
154           155  ...                     0.035
155           156  ...                     0.091

[5 rows x 9 columns]

In [7]:
df.columns #list of all the column of the dataframe

Index(['Overall rank', 'Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],
      dtype='object')

In [8]:
df.dtypes  #datatype of all column of the dataframe

Overall rank                      int64
Country or region                object
Score                           float64
GDP per capita                  float64
Social support                  float64
Healthy life expectancy         float64
Freedom to make life choices    float64
Generosity                      float64
Perceptions of corruption       float64
dtype: object

In [9]:
df.values  #Return a Numpy representation of the DataFrame

array([[1, 'Finland', 7.769, ..., 0.596, 0.153, 0.39299999999999996],
       [2, 'Denmark', 7.6, ..., 0.5920000000000001, 0.252, 0.41],
       [3, 'Norway', 7.553999999999999, ..., 0.603, 0.271, 0.341],
       ...,
       [154, 'Afghanistan', 3.2030000000000003, ..., 0.0, 0.158, 0.025],
       [155, 'Central African Republic', 3.083, ..., 0.225, 0.235, 0.035],
       [156, 'South Sudan', 2.853, ..., 0.01, 0.20199999999999999, 0.091]],
      dtype=object)

In [10]:
# provide summery of the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Overall rank                  156 non-null    int64  
 1   Country or region             156 non-null    object 
 2   Score                         156 non-null    float64
 3   GDP per capita                156 non-null    float64
 4   Social support                156 non-null    float64
 5   Healthy life expectancy       156 non-null    float64
 6   Freedom to make life choices  156 non-null    float64
 7   Generosity                    156 non-null    float64
 8   Perceptions of corruption     156 non-null    float64
dtypes: float64(7), int64(1), object(1)
memory usage: 11.1+ KB


In [11]:
df.axes #Return a list representing the axes of the DataFrame.

[RangeIndex(start=0, stop=156, step=1),
 Index(['Overall rank', 'Country or region', 'Score', 'GDP per capita',
        'Social support', 'Healthy life expectancy',
        'Freedom to make life choices', 'Generosity',
        'Perceptions of corruption'],
       dtype='object')]

In [12]:
df.ndim #Return an int representing the number of axes / array dimensions.

2

In [13]:
df.size #Return an int representing the number of elements in this object.

1404

In [14]:
df.memory_usage()  #Return the memory usage of each column in bytes.

Index                            128
Overall rank                    1248
Country or region               1248
Score                           1248
GDP per capita                  1248
Social support                  1248
Healthy life expectancy         1248
Freedom to make life choices    1248
Generosity                      1248
Perceptions of corruption       1248
dtype: int64

In [15]:
df.empty  #Indicator whether DataFrame is empty.

False

In [16]:
df.loc[:10,[ 'Country or region'] ]  #Access a group of rows and columns by labels

Country or region
0            Finland
1            Denmark
2             Norway
3            Iceland
4        Netherlands
5        Switzerland
6             Sweden
7        New Zealand
8             Canada
9            Austria
10         Australia

In [17]:
# corr method is used to see if any columns correlate
df.corr()

Overall rank  ...  Perceptions of corruption
Overall rank                      1.000000  ...                  -0.351959
Score                            -0.989096  ...                   0.385613
GDP per capita                   -0.801947  ...                   0.298920
Social support                   -0.767465  ...                   0.181899
Healthy life expectancy          -0.787411  ...                   0.295283
Freedom to make life choices     -0.546606  ...                   0.438843
Generosity                       -0.047993  ...                   0.326538
Perceptions of corruption        -0.351959  ...                   1.000000

[8 rows x 8 columns]

In [18]:
df.shape #number of rows and column in the dataset

(156, 9)

In [19]:
df["Score"].value_counts() #count the number of values Score column have

5.208    2
5.467    1
7.139    1
4.944    1
4.350    1
        ..
6.028    1
5.274    1
6.825    1
6.300    1
6.375    1
Name: Score, Length: 155, dtype: int64

In [20]:
type(df) #type of dataset

pandas.core.frame.DataFrame

In [21]:
df["Social support"].index

RangeIndex(start=0, stop=156, step=1)

In [22]:
df.loc[1]

Overall rank                          2
Country or region               Denmark
Score                               7.6
GDP per capita                    1.383
Social support                    1.573
Healthy life expectancy           0.996
Freedom to make life choices      0.592
Generosity                        0.252
Perceptions of corruption          0.41
Name: 1, dtype: object

In [23]:
df.iloc[1:3]

Overall rank Country or region  ...  Generosity  Perceptions of corruption
1             2           Denmark  ...       0.252                      0.410
2             3            Norway  ...       0.271                      0.341

[2 rows x 9 columns]

In [24]:
df1 = df.copy() #copy dataframe
df1.shape

(156, 9)

In [25]:
df.skew() #check skewness of dataframe

Overall rank                    0.000000
Score                           0.011450
GDP per capita                 -0.385232
Social support                 -1.134728
Healthy life expectancy        -0.613841
Freedom to make life choices   -0.685636
Generosity                      0.745942
Perceptions of corruption       1.650410
dtype: float64

In [26]:
df.isnull().sum()  #number of null value in each column

Overall rank                    0
Country or region               0
Score                           0
GDP per capita                  0
Social support                  0
Healthy life expectancy         0
Freedom to make life choices    0
Generosity                      0
Perceptions of corruption       0
dtype: int64

In [27]:
df.dropna(inplace=True) #to clear missing values

**Numpy**

In [28]:
import numpy as np

In [29]:
df.ndim  #the number of axes (dimensions) of the array.

2

In [30]:
print(df[:4:2])

   Overall rank Country or region  ...  Generosity  Perceptions of corruption
0             1           Finland  ...       0.153                      0.393
2             3            Norway  ...       0.271                      0.341

[2 rows x 9 columns]


In [31]:
#copying the dataframe
df3=np.copy(df)
df3

array([[1, 'Finland', 7.769, ..., 0.596, 0.153, 0.39299999999999996],
       [2, 'Denmark', 7.6, ..., 0.5920000000000001, 0.252, 0.41],
       [3, 'Norway', 7.553999999999999, ..., 0.603, 0.271, 0.341],
       ...,
       [154, 'Afghanistan', 3.2030000000000003, ..., 0.0, 0.158, 0.025],
       [155, 'Central African Republic', 3.083, ..., 0.225, 0.235, 0.035],
       [156, 'South Sudan', 2.853, ..., 0.01, 0.20199999999999999, 0.091]],
      dtype=object)

In [32]:
x = np.where(df== 'Kosovo')
x

(array([45]), array([1]))

In [33]:
np.mean(df)

Overall rank                    78.500000
Score                            5.407096
GDP per capita                   0.905147
Social support                   1.208814
Healthy life expectancy          0.725244
Freedom to make life choices     0.392571
Generosity                       0.184846
Perceptions of corruption        0.110603
dtype: float64

In [34]:
np.split(df,3)

[    Overall rank     Country or region  ...  Generosity  Perceptions of corruption
 0              1               Finland  ...       0.153                      0.393
 1              2               Denmark  ...       0.252                      0.410
 2              3                Norway  ...       0.271                      0.341
 3              4               Iceland  ...       0.354                      0.118
 4              5           Netherlands  ...       0.322                      0.298
 5              6           Switzerland  ...       0.263                      0.343
 6              7                Sweden  ...       0.267                      0.373
 7              8           New Zealand  ...       0.330                      0.380
 8              9                Canada  ...       0.285                      0.308
 9             10               Austria  ...       0.244                      0.226
 10            11             Australia  ...       0.332                    

In [35]:
df4=np.linspace(1,10)  #Generate an evenly spaced list between the interval 1 and 10
df4

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])


Practice 10 python programs using numpy libraries.



In [36]:
import numpy as np

a=np.array([1,2,3])  # 1D array
print(a)

b=np.array([(1,2,3),(4,5,6)])  #2D array
print(b)

#dimension of the array
print(a.ndim)  
print(b.ndim) 

 # byte size of each element.
print(a.itemsize)
print(b.itemsize)

#data type of the elements that are stored in an array.
print(a.dtype)
print(b.dtype)

#  size and shape of the array 
c = np.array([(1,2,3,4,5,6)])
print(c.size)
print(c.shape)

#c hange the number of rows and columns
d = np.array([(8,9,10),(11,12,13)])
d=d.reshape(3,2)
print(d)

#slicing
print(d[0,1])
print(d[0:,1])

#evenly spaced numbers over a specified interval. 
e=np.linspace(1,3,10)
print(e)

#max ,min and sum
a= np.array([1,2,3])
print(a.min())
print(a.max())
print(a.sum())

#suareroot
a=np.array([(1,2,3),(3,4,5,)])
print(np.sqrt(a))


[1 2 3]
[[1 2 3]
 [4 5 6]]
1
2
8
8
int64
int64
6
(1, 6)
[[ 8  9]
 [10 11]
 [12 13]]
9
[ 9 11 13]
[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]
1
3
6
[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]


Practice 10 python programs using pandas libraries.

In [37]:
import pandas as pd

data = {
    'apples': [3, 2, 0, 1], 
    'oranges': [0, 3, 7, 2]
}

#reading data and printing it
p = pd.DataFrame(data)
print(p)

#2 rows from top
print(p.head(2))

#2 row from bottom
print(p.tail(2))

#merging two dataframe
df1= pd.DataFrame({ "HPI":[80,90,70,60],"Int_Rate":[2,1,2,3],"IND_GDP":[50,45,45,67]}, index=[2001, 2002,2003,2004])
df2=pd.DataFrame({ "HPI":[80,90,70,60],"Int_Rate":[2,1,2,3],"IND_GDP":[50,45,45,67]}, index=[2005, 2006,2007,2008])
merged= pd.merge(df1,df2)
print(merged)


#joining two dataframe
df1 = pd.DataFrame({"Int_Rate":[2,1,2,3], "IND_GDP":[50,45,45,67]}, index=[2001, 2002,2003,2004])
df2 = pd.DataFrame({"Low_Tier_HPI":[50,45,67,34],"Unemployment":[1,3,5,6]}, index=[2001, 2003,2004,2004])
joined= df1.join(df2)
print(joined)

#concatenation
df1 = pd.DataFrame({"HPI":[80,90,70,60],"Int_Rate":[2,1,2,3], "IND_GDP":[50,45,45,67]}, index=[2001, 2002,2003,2004])
df2 = pd.DataFrame({"HPI":[80,90,70,60],"Int_Rate":[2,1,2,3],"IND_GDP":[50,45,45,67]}, index=[2005, 2006,2007,2008])
concat= pd.concat([df1,df2])
print(concat)

#changing index 
df= pd.DataFrame({"Day":[1,2,3,4], "Visitors":[200, 100,230,300], "Bounce_Rate":[20,45,60,10]}) 
df.set_index("Day", inplace= True)
print(df)

#changing column header
df = pd.DataFrame({"Day":[1,2,3,4], "Visitors":[200, 100,230,300], "Bounce_Rate":[20,45,60,10]})
df = df.rename(columns={"Visitors":"Users"})
print(df)

#checking for null value
p.isnull().sum()

#summery of dataframe
p.info()

   apples  oranges
0       3        0
1       2        3
2       0        7
3       1        2
   apples  oranges
0       3        0
1       2        3
   apples  oranges
2       0        7
3       1        2
   HPI  Int_Rate  IND_GDP
0   80         2       50
1   90         1       45
2   70         2       45
3   60         3       67
      Int_Rate  IND_GDP  Low_Tier_HPI  Unemployment
2001         2       50          50.0           1.0
2002         1       45           NaN           NaN
2003         2       45          45.0           3.0
2004         3       67          67.0           5.0
2004         3       67          34.0           6.0
      HPI  Int_Rate  IND_GDP
2001   80         2       50
2002   90         1       45
2003   70         2       45
2004   60         3       67
2005   80         2       50
2006   90         1       45
2007   70         2       45
2008   60         3       67
     Visitors  Bounce_Rate
Day                       
1         200           20
2      